@startuml
actor Buyer
participant LoginPage
participant BuyerPage
participant DeliveryAddressManager
participant Cart


participant "System" as System

participant SellerLoginPage
participant ProductManager
participant OrderManager
participant ShippingService
participant FeedbackManager
participant PaymentProcessor
actor Seller

group Buyer actor
Buyer -> LoginPage: Input Information
LoginPage -> System: Verify Login
Buyer -> BuyerPage: Browse and select products
BuyerPage -> System: Request to read product information
Buyer -> Cart: Add item to cart
Cart -> System: Modify user shopping cart information
Buyer -> BuyerPage: Proceed to checkout
BuyerPage -> System: Send checkout request
Buyer -> DeliveryAddressManager: Provide delivery address and payment details
DeliveryAddressManager -> System: Send address and payment details
Buyer -> BuyerPage: Confirm receipt of order
BuyerPage -> System: Send confirmation message
Buyer -> BuyerPage: Provide feedback or comments on the purchased item
BuyerPage -> System: Add users to provide feedback or comments on purchased items
end


group System behavior

System -> LoginPage: Send verify login information
System -> BuyerPage: Send product information
System -> Cart: Modify cart information
System -> DeliveryAddressManager: Add address and payment details success
System -> BuyerPage: Send order confirmation
System -> BuyerPage: Send comment success information

System -> SellerLoginPage: Send verify login information
System -> ProductManager: Modify product manager information
System -> OrderManager: Order information and receipts
System -> ShippingService: Dispatch request and update order status
System -> ShippingService: Update on the shipment status
System -> FeedbackManager: Show the product feedbacks
System -> PaymentProcessor: Show the details of the payment flow


end


group Seller actor
Seller -> SellerLoginPage: Input information
SellerLoginPage -> System: Verify login
Seller -> ProductManager: Add products
ProductManager -> System: Modify product manager information
Seller -> OrderManager: View orders
OrderManager -> System: Request to display order information and receipts
Seller -> ShippingService: Dispatch
ShippingService -> System: Send dispatch request and update order status
Seller -> ShippingService: Track shipments
ShippingService -> System: Request an update on the shipment status
Seller -> FeedbackManager: Check the product feedbacks
FeedbackManager -> System: Show the product feedbacks
Seller -> PaymentProcessor: Receive payment
PaymentProcessor -> System: Request to show the details of the payment flow
end
'group seller behavior
'Seller -> System: Add products to the System
'Seller -> System: Receive and process orders
'Seller -> System: Prepare and send packages
'Seller -> System: Responding to buyer comments
'end

@enduml
