@startuml
actor Buyer
participant "Login Page" as LoginPage
participant "Buyer Page" as BuyerPage
participant "Cart" as Cart


participant "System" as System



actor Seller

group Buyer actor
Buyer -> LoginPage: Input Information
LoginPage -> System: Verify Login
Buyer -> BuyerPage: Browse and select products
BuyerPage -> System: Request to read product information
Buyer -> Cart: Add item to cart
Cart -> System: Modify user shopping cart information
Buyer -> BuyerPage: Proceed to checkout
BuyerPage -> System: Send checkout request
Buyer -> BuyerPage: Provide shipping address and payment details
BuyerPage -> System: Send address and payment details
Buyer -> BuyerPage: Confirm receipt of order
BuyerPage -> System: Send confirmation message
Buyer -> BuyerPage: Provide feedback or comments on the purchased item
BuyerPage -> System: Add users to provide feedback or comments on purchased items
end

group Seller actor
Seller -> SellerLoginPage: Input information
SellerLoginPage -> System: Verify login
Seller -> ProductManager: Add products
ProductManager -> System: Modify product manager information
Seller -> OrderManager: View orders
OrderManager -> System: Request to display order information and receipts
Seller -> ShippingService: Dispatch
ShippingService -> System: Send dispatch request and update order status
Seller -> ShippingService: Track shipments
ShippingService -> System: Request an update on the shipment status
Seller -> FeedbackManager: Check the product feedbacks
FeedbackManager -> System: Show the product feedbacks
Seller -> PaymentProcessor: Receive payment
PaymentProcessor -> System: Request to show the details of the payment flow
end

group System behavior
Buyer -> System: Submit order request
System -> Seller: Send order information
Seller -> System: Confirm order receipt
System -> Buyer: send order confirmation
Seller -> System: Send package readiness notification
System -> Buyer: send package tracking information
Seller -> System: Respond to buyer's comments
System -> Buyer: Send seller response
Buyer -> System: Provide product feedback or reviews
System -> Seller: send buyer feedback or comments
end

'group seller behavior
'Seller -> System: Add products to the System
'Seller -> System: Receive and process orders
'Seller -> System: Prepare and send packages
'Seller -> System: Responding to buyer comments
'end

@enduml
